### ISSUE TITLE
add emacs mode

### ISSUE THREAD

**Issue by notestaff** [dnanexus/dx-toolkit#265]
It'd be great to have emacs extensions supporting dnanexus.  Simplest would be to be able to browse and modify projects using dired.  Ideally, one would also be able to monitor jobs running on dnanexus with something like the proced emacs command.

**Comment by psung** [comment]
Hi Ilya,

Some time ago I implemented some low- and high-level bindings to DNAnexus from emacs, which you may find useful as a starting point if you'd like to try some emacs/DNAnexus hacking. I haven't done much here recently, but you can find them in my dx-toolkit fork, on the branch `elisp-bindings`: https://github.com/psung/dx-toolkit/tree/elisp-bindings

Some notes on this--

* The low-level bindings provide a way to call any DNAnexus route; they map the JSON input to and from alists on the emacs side. It probably needs a rebase on top of latest `dx-toolkit` master, and a `make api_wrappers` to pick up any new API routes created since they were last updated. I also haven't tested it recently and I don't know if it all still works over TLS 1.2 (or if anything else has changed in recent versions of emacs, or in DNAnexus itself, that would break it).
* As for high-level functionality, you can browse the contents of projects and directories (`M-x dx-list-projects` to get started), but it's pretty bare; there's no functionality to download/update/delete individual objects, or to do anything with jobs.
* There was also some GTable-based functionality which is obsolete now.

Hope this is helpful in some way...

Phil
