### ISSUE TITLE
dxpy3 only allows utf-8 encoding

### ISSUE THREAD

**Issue by anujkumar93** [dnanexus/dx-toolkit#426]
Currently, dxpy3 uses 'utf-8' while reading files. `data.decode("utf-8")` is invoked during `dxpy.DXFile.read()`. This does not allow other types of files (like gzip) to be read using dxpy. For example, the following fails for dxpy3:
```
>>> import dxpy
>>> dxpy.upload_local_file(filename='s_3_2126.bcl.gz', project='project-FK8pJ100x54yqG4x7XyK62v2')
<dxpy.bindings.dxfile.DXFile object at 0x1028592b0: file-FPG51X80x54zvv365P3k9ZBp (project-FK8pJ100x54yqG4x7XyK62v2)>
>>> dxpy.DXFile(dxid='file-FPG51X80x54zvv365P3k9ZBp', project='project-FK8pJ100x54yqG4x7XyK62v2').read()
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/Users/akumar/stor/.delete/lib/python3.6/site-packages/dxpy/bindings/dxfile.py", line 955, in read
    return data.decode("utf-8")
UnicodeDecodeError: 'utf-8' codec can't decode byte 0x8b in position 1: invalid start byte
```

**Comment by anujkumar93** [comment]
@jtratner FYI

**Comment by orodeh** [comment]
@anujkumar93, @jtratner I believe the issue goes deeper. With python-2 data read from a text file is a string, so is data read from a binary (e.g. gzipped) file. However, with python-3, these are two distinct types. Data read from a text file is a string, data read from a binary file is bytes. The distinction percolates throughout the dxpy3 code. Since I had to choose which kind of file to support in dxpy3, I chose text files.

It is worth thinking about your use case. Constructive suggestions welcome.

**Comment by jtratner** [comment]
@orodeh To me, the underlying issue is that `DXFile` needs to support a binary `mode` argument (as well as an `encoding` argument), which would allow the user to specify how they want to handle their data. Currently only `r`, `w` and `a` are supported (i.e., only text modes).  (mode of a file pointer determines whether it produces text (AKA `str` / `unicode`) or `bytes`.)

It looks like the `write()` method is almost there, just the constructor of DXFile ought to take in an encoding argument (that defaults to `locale.getpreferredencoding(False)`) and also allow binary modes. 

I'd suggest making all the helper methods produce bytes that you then decode appropriately if a text pointer is required.

---

Just some examples of how the Python 3 API works in regards to str/bytes, demonstrating how the `encoding` argument works.

```
In [1]: BYTE_STRING = b"\xf0\x9f\x98\xb8"
   ...: STRING_STRING = u"hey😸"
   ...:

In [2]: BYTE_STRING
Out[2]: b'\xf0\x9f\x98\xb8'

In [3]: BYTE_STRING.decode('utf8')
Out[3]: '😸'

In [4]: with open('bytesfile.txt', 'wb') as fp:
   ...:     fp.write(BYTE_STRING)
   ...:

In [5]: with open('textfile.txt', 'w') as fp:
   ...:     fp.write(STRING_STRING)
   ...:
In [8]: with open('bytesfile.txt', 'r', encoding='utf8') as fp:
   ...:     print(fp.read())
   ...:
😸
In [9]: with open('bytesfile.txt', 'wb') as fp:
   ...:     fp.write(STRING_STRING.encode('utf16'))
   ...:
   ...:

In [10]: with open('bytesfile.txt', 'r', encoding='utf8') as fp:
    ...:     print(fp.read())
    ...:
---------------------------------------------------------------------------
UnicodeDecodeError                        Traceback (most recent call last)
<ipython-input-10-4b1b34684547> in <module>()
      1 with open('bytesfile.txt', 'r', encoding='utf8') as fp:
----> 2     print(fp.read())
      3

~/.pyenv/versions/3.6.4/lib/python3.6/codecs.py in decode(self, input, final)
    319         # decode input (taking the buffer into account)
    320         data = self.buffer + input
--> 321         (result, consumed) = self._buffer_decode(data, self.errors, final)
    322         # keep undecoded input until the next call
    323         self.buffer = data[consumed:]

UnicodeDecodeError: 'utf-8' codec can't decode byte 0xff in position 0: invalid start byte

In [11]: with open('bytesfile.txt', 'r', encoding='utf16') as fp:
    ...:     print(fp.read())
    ...:
hey😸
```

You can get a sense of how this works with the stor library has a fine example of how to handle this (by creating an appropriate buffer based upon mode). The underlying read_object and write_object methods *only* take bytes, whereas the higher level open() method converts to text if the user requests it.

https://github.com/counsyl/stor/blob/ec70e9dabfd26d5491270968cf568d2f71f27394/stor/obs.py#L328

```
    def _get_or_create_buffer(self):
        "Cached buffer of data read from or to be written to Object Storage"
        if self._buffer:
            return self._buffer

        if self.mode == 'r':
            buf = self.stream_cls(self._path.read_object().decode(self.encoding))
        elif self.mode == 'rb':
            buf = self.stream_cls(self._path.read_object())
        elif self.mode in ('w', 'wb'):
            buf = self.stream_cls()
        else:
            raise ValueError('cannot obtain buffer in mode: %r' % self.mode)
        self._buffer = buf
        return self._buffer
```

**Comment by jtratner** [comment]
Before writing the file, we check mode again and ensure converted to bytes:

```
        if self.mode == 'w':
            self._path.write_object(self._buffer.getvalue().encode(self.encoding))
        else:
            self._path.write_object(self._buffer.getvalue(), **self._kwargs)
```

**Comment by jtratner** [comment]
(apologies for spamming here, but I think in @anujkumar93 's example, the behavior is actually correct, but the fix should be to change the last line to include a `mode='rb'`

```
>>> dxpy.DXFile(dxid='file-FPG51X80x54zvv365P3k9ZBp', project='project-FK8pJ100x54yqG4x7XyK62v2', mode='rb').read()
```

**Comment by orodeh** [comment]
master branch now supports binary files in python3.

**Comment by orodeh** [comment]
Do you really need other encodings, other than utf-8?

**Comment by jtratner** [comment]
I’m slightly confused by your two statements.

> master branch now supports binary files in python3.

> Do you really need other encodings, other than utf-8?

Are you asking if there would be system encodings other than utf8?

For stor we’ve implemented this as using locale.getpreferredencoding and
additionally being strict about ‘w’ vs ‘wb’

**Comment by orodeh** [comment]
I added the ability for python3 to handle upload/download with unicode and binary data. This includes the ability to specify modes like "rb", "wb". However, I did not support encodings other than utf-8. 

The question is: now that there is binary mode, do you need encodings other than utf-8 as well? I don't think it would be that easy, because there is an environment variable setting in `dx-toolkit/environment`.

**Comment by anujkumar93** [comment]
You mean there is an environment variable in dx-toolkit/environment that
specifies the encoding? What's its name?

**Comment by orodeh** [comment]
It is the python environment variable, and it is set [here](https://github.com/dnanexus/dx-toolkit/blob/master/environment#L73).

**Comment by jtratner** [comment]
@orodeh - right now you still can't cat a BAM file or tarball, for example:

```
›› dx cat <some tar.gz file> | cut -c 1-300
Traceback (most recent call last):
  File "/Users/jtratner/.pyenv/versions/3.6.4/lib/python3.6/site-packages/dxpy/scripts/dx.py", line 1930, in cat
    chunk = dxfile.read(1024*1024, project=project or dxpy.DXFile.NO_PROJECT_HINT)
  File "/Users/jtratner/.pyenv/versions/3.6.4/lib/python3.6/site-packages/dxpy/bindings/dxfile.py", line 955, in read
    return data.decode("utf-8")
UnicodeDecodeError: 'utf-8' codec can't decode byte 0x8b in position 1: invalid start byte
```

**Comment by orodeh** [comment]
@jtratner The fix is in master, it is not on production yet. Meanwhile, you can test it by checking out and building master branch.
