### ISSUE TITLE
Test run an applet locally

### ISSUE THREAD

**Issue by njosyula** [dnanexus/dx-toolkit#563]
I am understanding that the "dx-run-app-locally" script is no more available. Is there an alternative method or script that I can use to test my applet locally before building it to DNANexus platform?

I am testing the "dx-run-app-locally" script on my linux machine but I when I gave the inputs, I am getting the error:
"TypeError: must be unicode, not str"

**Comment by orodeh** [comment]
@njosyula, We have moved away from this idea. Moving forward, you could run things locally with a WDL runner (if you have a WDL script), or use a cloud workstation to approximate a "local" environment.

The error you are seeing is due to a python 2/3 issue. However, I would suggest simply staying away from the `dx-run-app-locally` script.

**Comment by njosyula** [comment]
Thank you for your suggestions!
