### ISSUE TITLE
No dx-verify-file from dx command line tool installed with pip3

### ISSUE THREAD

**Issue by violetbrina** [dnanexus/dx-toolkit#630]
Migrating to python3 including my dx cli, but the dx-verify-file command is not there.

This is all I have in my venv bin:
```
./				     dx-build-applet*		dx-jobutil-report-error*  python@
../				     dx-build-report-html*	dx-log-stream*		  python-argcomplete-check-easy-install-script*
__pycache__/			     dx-clone-asset*		dx-mount-all-inputs*	  python-argcomplete-tcsh*
activate			     dx-docker*			dx-notebook-reconnect*	  python3@
activate-global-python-argcomplete*  dx-download-all-inputs*	dx-print-bash-vars*	  register-python-argcomplete*
activate.csh			     dx-fetch-bundled-depends*	dx-upload-all-outputs*	  tqdm*
activate.fish			     dx-generate-dxapp*		easy_install*		  wsdump.py*
chardetect*			     dx-jobutil-add-output*	easy_install-3.7*	  xattr*
dx*				     dx-jobutil-dxlink*		pip*
dx-app-wizard*			     dx-jobutil-new-job*	pip3*
dx-build-app*			     dx-jobutil-parse-link*	pip3.7*
```

Please add dx-verify-file to pip, it is very helpful for our workflow.

**Comment by kpjensen** [comment]
`dx-verify-file` is a standalone c++ executable that is not included with the pypi / pip installation, only the tarball download https://documentation.dnanexus.com/downloads#installation-of-java-r-and-c-sdk-from-tarball. It rarely changes, so you could move the `dx-verify-file` binary to somewhere in your `PATH` globally so that it is available in each venv.
